### ISSUE TITLE
gnu sort completely unexpected behaviour

### ISSUE THREAD

**Issue by cjsin** [coreutils/coreutils#30]
"Please **do not** send pull-requests or open new issues on Github."
  -  Well as the choice seems to be between reporting it here and exposing my email address to spammers on your public mailing list, I'll report it here anyway.

The issue being reported here, is that GNU sort, does not sort, or sorts incorrectly, or sorts by weird locale rules that make it utterly useless even to people native to that locale. Results that are completely unexpected and likely to cause software written using the tool, to take completely wrong actions depending on which part of the world the software is being executed, or whether the system is using the utf-8 character set.

Quite a simple scenario - four lines of text:

"a  1"
"a2 1"
"a2 a"
"a  a"

How would you expect it to be ordered, if 'sorted'?

I would expect:
  a  1
  a  a
  a2 1
  a2 a

and this is indeed the result if we use a non-utf-8 locale, or if we use LC_ALL=C

$> printf "a  1\na2 1\na2 a\na  a" | LC_ALL=en_AU sort
a  1
a  a
a2 1
a2 a

However for UTF-8 locales, gnu sort seems to go insane:

$> printf "a  1\na2 1\na2 a\na  a" | LC_ALL=en_AU.UTF-8 sort
a  1
a2 1
a2 a
a  a

Questions/assumptions:
-------------

Should UTF-8 users be expecting GNU sort to sort by the second column instead of the first?

Why is GNU sort treating a space character as magically equivalent to a '2' digit?

Maybe GNU sort is treating a whitespace as a character and not a spacing token?
  - this does not seem to be the case, as the following demonstrates.
  - In the first command below, 'a2[space]' sorts AFTER 'a[space]'
  - In the second command below, 'a2[space]' sorts BEFORE 'a[space]'

  - What's the difference? Nothing in the first column. Therefore it seems GNU sort is somehow sorting based on the second column. 

$>  printf "a  \na2 \na2 a\na  " | LC_ALL=en_AU.UTF-8 sort
a  
a  
a2 
a2 a

$>  printf "a  x\na2 x\na2 a\na  x" | LC_ALL=en_AU.UTF-8 sort
a2 a
a2 x
a  x
a  x

As a developer who writes scripts which have to perform actions such as sorting lists of files and deleting some of them, is it possible for me to utilise gnu sort safely in a such a script which may (or may not) be run in a UTF-8 locale? Short of setting LC_ALL=C in every script, is there any way to make gnu sort work as expected, which is that, unless specific sort keys are specified, it should at the very least sort lines such that all the lines starting with 'a' are together, and all the lines starting with 'a2' are together - whether a locale sorts 'a' before or after 'a2' is another matter - but no locale or utf-8 setting should result in the behaviour seen above, where lines starting with 'a' are insterspersed with lines that start with 'a2', and are seemingly sorted by the second column instead of the first.

**Comment by semilin** [comment]
I agree with you, issues should certainly be allowed to be submitted on github. The fact that GNU does not allow this is ridiculous.

**Comment by agordon** [comment]
Hello,

Answering briefly:
1. Yes - we discourage github issues, and focus our development,discussions and bug reports on the GNU mailing lists. If you are worried about privacy, consider creating a throw-away email just for that.
2. With UTF-8 locales, spaces and other punctuation characters are often ignored. This happens not because of GNU sort, but because of the locale rules defined by GNU libc.
This and similar complaints have been discussed many times in the past, see here:
https://crashcourse.housegordon.com/coreutils-multibyte-support.html#sort
Using `LC_ALL=C` is the correct solution. You don't need to set it in all your scripts, you can use it in sort exclusively (e.g. `program | LC_ALL=C sort | program`) or create a sort wrapper script that forces `LC_ALL=C`.
3. As for your other questions, if the above website and linked discussions do not answer you question, please do sent an email to coreutils@gnu.org and many people will be able to help there.

As such, I'm closing this issue.
